#lang hydromel

import "decoder.mel"
import "opcodes.mel"

component comparator
    port instr : splice flip instruction
    port a     : in word_t
    port b     : in word_t
    port taken : out bit

    taken = case funct3 of
        funct3_beq  => a  == b
        funct3_bne  => a  /= b
        funct3_blt  => (a as integer) <  (b as integer)
        funct3_bge  => (a as integer) >= (b as integer)
        funct3_bltu => a  <  b
        funct3_bgeu => a  >= b
        _           => 0
end
