; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at https://mozilla.org/MPL/2.0/.

#lang racket

(require
  "../asm/assembler.rkt"
  "../asm/opcodes.rkt"
  "../cpu/decoder.mel"
  hydromel/lib/signal
  hydromel/lib/slot
  hydromel/lib/helpers
  rackunit)

(define alu_nop  1)
(define alu_add  2)
(define alu_sub  3)
(define alu_slt  4)
(define alu_sltu 5)
(define alu_and  6)
(define alu_or   7)
(define alu_xor  8)
(define alu_sll  9)
(define alu_srl  10)
(define alu_sra  11)

(define test-cases
  (list                         ; rd funct3          rs1  rs2       imm alu_fn   use_pc  use_imm has_rd is_load is_store is_jump is_branch is_mret
    ; Test rd, rs1, rs2 for R-type instruction.
    (list (ADD    0  0      0)     0 funct3-add-sub    0    0      'any alu_add  0       0       0      0       0        0       0         0)
    (list (ADD    5 10     15)     5 funct3-add-sub   10   15      'any alu_add  0       0       1      0       0        0       0         0)
    (list (ADD   31 31     31)    31 funct3-add-sub   31   31      'any alu_add  0       0       1      0       0        0       0         0)
    (list (ADD   40 41     42)     8 funct3-add-sub    9   10      'any alu_add  0       0       1      0       0        0       0         0)
    ; Test imm for I-type instruction (12 bits)
    (list (ADDI   5 10      0)     5 funct3-add-sub   10 'any         0 alu_add  0       1       1      0       0        0       0         0)
    (list (ADDI   5 10 #x07ff)     5 funct3-add-sub   10 'any    #x07ff alu_add  0       1       1      0       0        0       0         0)
    (list (ADDI   5 10 #x0800)     5 funct3-add-sub   10 'any   #x-0800 alu_add  0       1       1      0       0        0       0         0)
    (list (ADDI   5 10 #x0fff)     5 funct3-add-sub   10 'any        -1 alu_add  0       1       1      0       0        0       0         0)
    ; Test imm for S-type instruction (12 bits)
    (list (SW     5 10      0)  'any funct3-lw-sw     10    5         0 alu_add  0       1       0      0       1        0       0         0)
    (list (SW     5 10 #x07ff)  'any funct3-lw-sw     10    5    #x07ff alu_add  0       1       0      0       1        0       0         0)
    (list (SW     5 10 #x0800)  'any funct3-lw-sw     10    5   #x-0800 alu_add  0       1       0      0       1        0       0         0)
    (list (SW     5 10 #x0fff)  'any funct3-lw-sw     10    5        -1 alu_add  0       1       0      0       1        0       0         0)
    ; Test imm for B-type instruction (13 bits, even)
    (list (BEQ    5 10      0)  'any funct3-beq        5   10         0 alu_add  1       1       0      0       0        0       1         0)
    (list (BEQ    5 10 #x0fff)  'any funct3-beq        5   10    #x0ffe alu_add  1       1       0      0       0        0       1         0)
    (list (BEQ    5 10 #x1000)  'any funct3-beq        5   10   #x-1000 alu_add  1       1       0      0       0        0       1         0)
    (list (BEQ    5 10 #x1fff)  'any funct3-beq        5   10        -2 alu_add  1       1       0      0       0        0       1         0)
    ; Test imm for U-type instruction (32 bits, multiple of #x1000)
    (list (LUI    5    #x0000)     5 'any           'any 'any         0 alu_nop  0       1       1      0       0        0       0         0)
    (list (LUI    5    #x0fff)     5 'any           'any 'any         0 alu_nop  0       1       1      0       0        0       0         0)
    (list (LUI    5    #x1fff)     5 'any           'any 'any    #x1000 alu_nop  0       1       1      0       0        0       0         0)
    (list (LUI    5    #xffff)     5 'any           'any 'any    #xf000 alu_nop  0       1       1      0       0        0       0         0)
    (list (LUI    5        -1)     5 'any           'any 'any   #x-1000 alu_nop  0       1       1      0       0        0       0         0)
    ; Test imm for J-type instruction (21 bits, even)
    (list (JAL    5         0)     5 'any           'any 'any         0 alu_add  1       1       1      0       0        1       0         0)
    (list (JAL    5   #xfffff)     5 'any           'any 'any   #xffffe alu_add  1       1       1      0       0        1       0         0)
    (list (JAL    5  #x100000)     5 'any           'any 'any #x-100000 alu_add  1       1       1      0       0        1       0         0)
    (list (JAL    5  #x1fffff)     5 'any           'any 'any        -2 alu_add  1       1       1      0       0        1       0         0)
    ; Test functions for all instruction types.
    (list (LUI    0    #x1234)  'any 'any           'any 'any      'any alu_nop  0       1       0      0       0        0       0         0)
    (list (LUI   31    #x1234)  'any 'any           'any 'any      'any alu_nop  0       1       1      0       0        0       0         0)
    (list (AUIPC  0    #x1234)  'any 'any           'any 'any      'any alu_add  1       1       0      0       0        0       0         0)
    (list (AUIPC 31    #x1234)  'any 'any           'any 'any      'any alu_add  1       1       1      0       0        0       0         0)
    (list (JAL    0    #x1234)  'any 'any           'any 'any      'any alu_add  1       1       0      0       0        1       0         0)
    (list (JAL   31    #x1234)  'any 'any           'any 'any      'any alu_add  1       1       1      0       0        1       0         0)
    (list (JALR   0 15 #x1234)  'any funct3-jalr    'any 'any      'any alu_add  0       1       0      0       0        1       0         0)
    (list (JALR  31 15 #x1234)  'any funct3-jalr    'any 'any      'any alu_add  0       1       1      0       0        1       0         0)
    (list (BEQ    5 10 #x1234)  'any funct3-beq     'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (BNE    5 10 #x1234)  'any funct3-bne     'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (BLT    5 10 #x1234)  'any funct3-blt     'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (BGE    5 10 #x1234)  'any funct3-bge     'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (BLTU   5 10 #x1234)  'any funct3-bltu    'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (BGEU   5 10 #x1234)  'any funct3-bgeu    'any 'any      'any alu_add  1       1       0      0       0        0       1         0)
    (list (LB     0 15 #x1234)  'any funct3-lb-sb   'any 'any      'any alu_add  0       1       0      1       0        0       0         0)
    (list (LB    31 15 #x1234)  'any funct3-lb-sb   'any 'any      'any alu_add  0       1       1      1       0        0       0         0)
    (list (LH     0 15 #x1234)  'any funct3-lh-sh   'any 'any      'any alu_add  0       1       0      1       0        0       0         0)
    (list (LH    31 15 #x1234)  'any funct3-lh-sh   'any 'any      'any alu_add  0       1       1      1       0        0       0         0)
    (list (LW     0 15 #x1234)  'any funct3-lw-sw   'any 'any      'any alu_add  0       1       0      1       0        0       0         0)
    (list (LW    31 15 #x1234)  'any funct3-lw-sw   'any 'any      'any alu_add  0       1       1      1       0        0       0         0)
    (list (LBU    0 15 #x1234)  'any funct3-lbu     'any 'any      'any alu_add  0       1       0      1       0        0       0         0)
    (list (LBU   31 15 #x1234)  'any funct3-lbu     'any 'any      'any alu_add  0       1       1      1       0        0       0         0)
    (list (LHU    0 15 #x1234)  'any funct3-lhu     'any 'any      'any alu_add  0       1       0      1       0        0       0         0)
    (list (LHU   31 15 #x1234)  'any funct3-lhu     'any 'any      'any alu_add  0       1       1      1       0        0       0         0)
    (list (SB     5 15 #x1234)  'any funct3-lb-sb   'any 'any      'any alu_add  0       1       0      0       1        0       0         0)
    (list (SH     5 15 #x1234)  'any funct3-lh-sh   'any 'any      'any alu_add  0       1       0      0       1        0       0         0)
    (list (SW     5 15 #x1234)  'any funct3-lw-sw   'any 'any      'any alu_add  0       1       0      0       1        0       0         0)
    (list (ADDI   0 10 #x1234)  'any funct3-add-sub 'any 'any      'any alu_add  0       1       0      0       0        0       0         0)
    (list (ADDI  31 10 #x1234)  'any funct3-add-sub 'any 'any      'any alu_add  0       1       1      0       0        0       0         0)
    (list (SLLI   0 10 #x1234)  'any funct3-sll     'any 'any      'any alu_sll  0       1       0      0       0        0       0         0)
    (list (SLLI  31 10 #x1234)  'any funct3-sll     'any 'any      'any alu_sll  0       1       1      0       0        0       0         0)
    (list (SLTI   0 10 #x1234)  'any funct3-slt     'any 'any      'any alu_slt  0       1       0      0       0        0       0         0)
    (list (SLTI  31 10 #x1234)  'any funct3-slt     'any 'any      'any alu_slt  0       1       1      0       0        0       0         0)
    (list (SLTIU  0 10 #x1234)  'any funct3-sltu    'any 'any      'any alu_sltu 0       1       0      0       0        0       0         0)
    (list (SLTIU 31 10 #x1234)  'any funct3-sltu    'any 'any      'any alu_sltu 0       1       1      0       0        0       0         0)
    (list (XORI   0 10 #x1234)  'any funct3-xor     'any 'any      'any alu_xor  0       1       0      0       0        0       0         0)
    (list (XORI  31 10 #x1234)  'any funct3-xor     'any 'any      'any alu_xor  0       1       1      0       0        0       0         0)
    (list (SRLI   0 10 #x1234)  'any funct3-srl-sra 'any 'any      'any alu_srl  0       1       0      0       0        0       0         0)
    (list (SRLI  31 10 #x1234)  'any funct3-srl-sra 'any 'any      'any alu_srl  0       1       1      0       0        0       0         0)
    (list (SRAI   0 10 #x1234)  'any funct3-srl-sra 'any 'any      'any alu_sra  0       1       0      0       0        0       0         0)
    (list (SRAI  31 10 #x1234)  'any funct3-srl-sra 'any 'any      'any alu_sra  0       1       1      0       0        0       0         0)
    (list (ORI    0 10 #x1234)  'any funct3-or      'any 'any      'any alu_or   0       1       0      0       0        0       0         0)
    (list (ORI   31 10 #x1234)  'any funct3-or      'any 'any      'any alu_or   0       1       1      0       0        0       0         0)
    (list (ANDI   0 10 #x1234)  'any funct3-and     'any 'any      'any alu_and  0       1       0      0       0        0       0         0)
    (list (ANDI  31 10 #x1234)  'any funct3-and     'any 'any      'any alu_and  0       1       1      0       0        0       0         0)
    (list (ADD    0  5     10)  'any funct3-add-sub 'any 'any      'any alu_add  0       0       0      0       0        0       0         0)
    (list (ADD   31  5     10)  'any funct3-add-sub 'any 'any      'any alu_add  0       0       1      0       0        0       0         0)
    (list (SUB    0  5     10)  'any funct3-add-sub 'any 'any      'any alu_sub  0       0       0      0       0        0       0         0)
    (list (SUB   31  5     10)  'any funct3-add-sub 'any 'any      'any alu_sub  0       0       1      0       0        0       0         0)
    (list (SLL    0  5     10)  'any funct3-sll     'any 'any      'any alu_sll  0       0       0      0       0        0       0         0)
    (list (SLL   31  5     10)  'any funct3-sll     'any 'any      'any alu_sll  0       0       1      0       0        0       0         0)
    (list (SLT    0  5     10)  'any funct3-slt     'any 'any      'any alu_slt  0       0       0      0       0        0       0         0)
    (list (SLT   31  5     10)  'any funct3-slt     'any 'any      'any alu_slt  0       0       1      0       0        0       0         0)
    (list (SLTU   0  5     10)  'any funct3-sltu    'any 'any      'any alu_sltu 0       0       0      0       0        0       0         0)
    (list (SLTU  31  5     10)  'any funct3-sltu    'any 'any      'any alu_sltu 0       0       1      0       0        0       0         0)
    (list (XOR    0  5     10)  'any funct3-xor     'any 'any      'any alu_xor  0       0       0      0       0        0       0         0)
    (list (XOR   31  5     10)  'any funct3-xor     'any 'any      'any alu_xor  0       0       1      0       0        0       0         0)
    (list (SRL    0  5     10)  'any funct3-srl-sra 'any 'any      'any alu_srl  0       0       0      0       0        0       0         0)
    (list (SRL   31  5     10)  'any funct3-srl-sra 'any 'any      'any alu_srl  0       0       1      0       0        0       0         0)
    (list (SRA    0  5     10)  'any funct3-srl-sra 'any 'any      'any alu_sra  0       0       0      0       0        0       0         0)
    (list (SRA   31  5     10)  'any funct3-srl-sra 'any 'any      'any alu_sra  0       0       1      0       0        0       0         0)
    (list (OR     0  5     10)  'any funct3-or      'any 'any      'any alu_or   0       0       0      0       0        0       0         0)
    (list (OR    31  5     10)  'any funct3-or      'any 'any      'any alu_or   0       0       1      0       0        0       0         0)
    (list (AND    0  5     10)  'any funct3-and     'any 'any      'any alu_and  0       0       0      0       0        0       0         0)
    (list (AND   31  5     10)  'any funct3-and     'any 'any      'any alu_and  0       0       1      0       0        0       0         0)))
    ;                             rd funct3          rs1  rs2       imm alu_fn   use_pc use_imm has_rd is_load is_store is_jump is_branch is_mret

(define (fake-asm data)
  (if (procedure? data)
    (data 0  0 )
    data))

(define test-count (length test-cases))

(define lst-data (map fake-asm (map first test-cases)))

(define inst (decoder-make))
(slot-set! (inst data_i) (list->signal lst-data))

(define slot-names '(rd funct3 rs1 rs2 imm
                     alu_fn use_pc use_imm has_rd
                     is_load is_store is_jump is_branch is_mret))

(for ([(name i) (in-indexed slot-names)])
  (for ([(res j) (in-indexed (signal-take (slot-data (dict-ref inst name)) test-count))])
    (define ex (list-ref (list-ref test-cases j) (add1 i)))
    (when (not (equal? 'any ex))
      (test-equal? (format "Decoder #~a: ~a" j name) res ex))))
